package:
  name: acctotax
  version: "0.1.0"

source:
  git_rev: v0.1.0
  git_url: https://github.com/koriege/acctotax.git

requirements:
  run:
    - perl >=5.10
    - perl-bioperl
    
test:
  commands:
    - speciesToLineage.pl -h
 
about:
  home: https://github.com/koriege/acctotax